### PR TITLE
Add a check if the move is diagonal to the arbitrator

### PR DESCRIPTION
**Pull request by wildarch**
Also implements a few utility function for analyzing moves and checks for a division by zero in move_helper.py

### CODE REVIEW

**Comment by nouwaarom** [comment]
Thanks for the help! The only thing I noted is that when you call helperGetOldPiece() at line 16 of arbitrator.py you dont check the return value. This causes the program to throw an exception and die. Could you please fix that?

**Comment by wildarch** [comment]
It is indeed possible that helperGetOldPiece returns nothing, but in that case the move is invalid. It should also issue a warning for this. Will fix this never the less. Have you been able to actually crash the program on this?

**Comment by wildarch** [comment]
Put a try except around the helper calls

**Comment by nouwaarom** [comment]
If you do a horizontal move so (17 to 18 for example it crashes) but vertical (17 to 27 for example it correctly says the move is illegal.

**Comment by nouwaarom** [comment]
One other thing I noted is that if the AI tries to hit two pieces that are not in a line. The arbitrator also says the move is illegal while the move is actually legal.

**Comment by wildarch** [comment]
I have limited the diagonal check to run with at most one captured piece. As this now only covers one simple cheat, I want to extend these checks in the future.

**Pull request merged**
